---
title: "Posterprojekt: Anaconda – Path 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 4)
library(ggplot2)
library(MASS)
library(mvnormtest)
library(car)
library(ellipse)
```

### 1. Data og forberedelse

```{r}
data("T6-19", package = "st514")
T6.19 <- tbl
colnames(T6.19) <- c("Snout Vent Length (cm)", "Weight (kg)", "Gender")
levels(T6.19$Gender) <- c("Female", "Male")
```

### 2. Exploratory Data Analysis (EDA)
```{r}
summary(T6.19)
boxplot(`Snout Vent Length (cm)` ~ Gender, data = T6.19)
boxplot(`Weight (kg)` ~ Gender, data = T6.19)
ggplot(T6.19, aes(x = `Snout Vent Length (cm)`, y = `Weight (kg)`, color = Gender)) +
  geom_point(size = 2) + theme_minimal()
```

### 3. Univariate T-tests
```{r}
t.test(`Snout Vent Length (cm)` ~ Gender, data = T6.19, var.equal = TRUE)
t.test(`Weight (kg)` ~ Gender, data = T6.19, var.equal = TRUE)
```

### 4. Hotelling’s T² og Box’s M
```{r}
Xf <- T6.19[T6.19$Gender == "Female", 1:2]
Xm <- T6.19[T6.19$Gender == "Male", 1:2]
n1 <- nrow(Xf); n2 <- nrow(Xm)
xbar1 <- colMeans(Xf); xbar2 <- colMeans(Xm)
S1 <- cov(Xf); S2 <- cov(Xm)
Spooled <- ((n1 - 1)*S1 + (n2 - 1)*S2) / (n1 + n2 - 2)
T2 <- t(xbar1 - xbar2) %*% solve((1/n1 + 1/n2)*Spooled) %*% (xbar1 - xbar2)
p <- ncol(Xf)
Fstat <- (n1 + n2 - p - 1)*T2 / ((n1 + n2 - 2)*p)
pval <- 1 - pf(Fstat, df1 = p, df2 = n1 + n2 - p - 1)
T2; Fstat; pval

# Box’s M test manuelt
logdet_S1 <- log(det(S1))
logdet_S2 <- log(det(S2))
logdet_pooled <- log(det(Spooled))
M <- (n1 - 1)*logdet_S1 + (n2 - 1)*logdet_S2 - (n1 + n2 - 2)*logdet_pooled
u <- (1/(n1 - 1) + 1/(n2 - 1) - 1/(n1 + n2 - 2)) * ((2*p^2 + 3*p - 1)/(6*(p + 1)))
Chi2 <- M * (1 - u)
df_boxm <- p * (p + 1) / 2
pval_boxm <- 1 - pchisq(Chi2, df = df_boxm)
Chi2; pval_boxm
```

### 5. Simultane CI + Plot med ellipse og Bonferroni
```{r}
diff_mean <- xbar1 - xbar2
n <- (n1 * n2) / (n1 + n2)
S <- Spooled
alpha <- 0.05
p <- 2
T2_crit <- ((n1 + n2 - 2) * p / (n1 + n2 - p - 1)) * qf(1 - alpha, p, n1 + n2 - p - 1)

# Bonferroni CI
bonf_tval <- qt(1 - alpha / (2 * p), df = n1 + n2 - 2)
cimu1 <- diff_mean[1] + c(-1, 1) * bonf_tval * sqrt(S[1, 1] / n)
cimu2 <- diff_mean[2] + c(-1, 1) * bonf_tval * sqrt(S[2, 2] / n)

# Plot ellipse og Bonferroni rektangel med udvidede akser
xlim <- range(c(0, cimu1)) * c(0.8, 1.2)
ylim <- range(c(0, cimu2)) * c(0.8, 1.2)

plot(ellipse(S / n, centre = diff_mean, level = 1 - alpha, t = sqrt(T2_crit)),
     type = "l", xlab = "Snout Length", ylab = "Weight",
     main = "Hotelling's T² Ellipse + Bonferroni CI",
     xlim = xlim, ylim = ylim)
points(0, 0, pch = 3, col = "blue")
points(diff_mean[1], diff_mean[2], pch = 19, col = "darkred")

# Rektangel = Bonferroni CI
lines(c(cimu1[1], cimu1[1]), c(cimu2[1], cimu2[2]), lty = 2)
lines(c(cimu1[2], cimu1[2]), c(cimu2[1], cimu2[2]), lty = 2)
lines(c(cimu1[1], cimu1[2]), c(cimu2[1], cimu2[1]), lty = 2)
lines(c(cimu1[1], cimu1[2]), c(cimu2[2], cimu2[2]), lty = 2)
```

### 6. Konklusion
- Hotelling’s T²: signifikant forskel i middelvektor (p < 0.05)
- Box’s M: pooling er rimelig (p > 0.05)
- CI: Længde forklarer forskellen mellem kønnene
